# Generated by Django 4.2.7 on 2023-11-14 07:23

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cake', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cakes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('collections', models.CharField(choices=[('choclate cake', 'choclate cake'), ('butterscotch', 'butterscotch'), ('red velvet', 'red velvet'), ('milk cake', 'milk cake'), ('cheese cake', 'cheese cake'), ('cup cake', 'cup cake'), ('plum cake', 'plum cake')], default='choclate cake', max_length=200)),
                ('image', models.ImageField(upload_to='images')),
                ('brand', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='CakeVarients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField()),
                ('color', models.CharField(max_length=100)),
                ('size', models.CharField(choices=[('half kg', 'half kg'), ('1 kg', '5 kg'), ('3 kg', '3 kg'), ('4 kg', '4 kg'), ('5 kg', '5 kg')], default='one kg', max_length=200)),
                ('cake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cake.cakes')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.CharField(max_length=300)),
                ('cakevarient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cake.cakevarients')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('order-placed', 'order-placed'), ('dispatched', 'dispached'), ('cancelled', 'cancelled'), ('in-transit', 'in-transit'), ('delivered', 'delivered')], default='order-placed', max_length=200)),
                ('orderd_date', models.DateTimeField(auto_now_add=True)),
                ('expected_date', models.DateField(null=True)),
                ('address', models.CharField(max_length=200)),
                ('cakevarient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cake.cakevarients')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Offers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField()),
                ('start_date', models.DateTimeField()),
                ('due_date', models.DateTimeField()),
                ('cakevarient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cake.cakevarients')),
            ],
        ),
        migrations.CreateModel(
            name='Carts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('in-cart', 'in-cart'), ('order-placed', 'order-place'), ('cancelled', 'cancelled')], default='in-cart', max_length=200)),
                ('date', models.DateTimeField(auto_now=True)),
                ('cakevarient', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cake.cakevarients')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
