# Generated by Django 4.2.7 on 2023-11-14 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cake', '0004_alter_cakes_collections'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cakes',
            old_name='collections',
            new_name='category',
        ),
        migrations.AlterField(
            model_name='cakevarients',
            name='size',
            field=models.CharField(choices=[('half kg', 'half kg'), ('1 kg', '5 kg'), ('3 kg', '3 kg'), ('4 kg', '4 kg'), ('5 kg', '5 kg')], default='1kg', max_length=200),
        ),
    ]
