# Generated by Django 4.2.7 on 2023-11-14 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cake', '0005_rename_collections_cakes_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cakevarients',
            name='shape',
            field=models.CharField(choices=[('round', 'round'), ('square', 'square'), ('heartshape', 'heartshape')], default='round', max_length=200),
        ),
    ]
