# Generated by Django 4.2.7 on 2023-11-26 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cake', '0008_alter_cakes_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cakes',
            name='category',
            field=models.ForeignKey(choices=[('cream cake', 'cream cake'), ('milk cake', 'milk cake'), ('cheese cake', 'cheese cake'), ('cup cake', 'cup cake'), ('plum cake', 'plum cake')], default='cream cake', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cake.category'),
        ),
    ]
