# Generated by Django 4.2.7 on 2023-11-26 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cake', '0009_alter_cakes_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cakes',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cake.category'),
        ),
    ]
